#!/bin/bash
#######################################################################
#
#
#
#
#
#
#
#
#
#######################################################################

ppas:
  - ppa:saiarcot895/myppa
  - ppa:git-core/ppa

using_elk: false

freeipa:
    ip:       10.0.2.15
    hostname: ipa
    fqdn:     ipa.example.com
